version: '3'

services:
  django:
    build:
      context: .
      dockerfile: compose/prod/django/Dockerfile
    image: djangocon_2024_local_django
    container_name: djangocon_2024_local_django
    volumes:
      - .:/app:z
    env_file:
      - .envs/.django
    ports:
      - '8000:8000'
    command: /start
